/* Autogenerated with kurento-module-creator */

#ifndef __ENDPOINT_HPP__
#define __ENDPOINT_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "MediaElement.hpp"

namespace kurento
{
class Endpoint;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::Endpoint> &object, JsonSerializer &serializer);
}

namespace kurento
{
class Endpoint : public virtual MediaElement
{

public:
  Endpoint () {};
  virtual ~Endpoint () {};

  virtual std::string getType () const {
    return "Endpoint";
  }

  virtual std::string getModule () const {
    return "kurento";
  }

  virtual void Serialize (JsonSerializer &serializer) = 0;

};

} /* kurento */

#endif /*  __ENDPOINT_HPP__ */
