/* Autogenerated with kurento-module-creator */

#ifndef __FILTER_HPP__
#define __FILTER_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "MediaElement.hpp"

namespace kurento
{
class Filter;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::Filter> &object, JsonSerializer &serializer);
}

namespace kurento
{
class Filter : public virtual MediaElement
{

public:
  Filter () {};
  virtual ~Filter () {};

  virtual std::string getType () const {
    return "Filter";
  }

  virtual std::string getModule () const {
    return "kurento";
  }

  virtual void Serialize (JsonSerializer &serializer) = 0;

};

} /* kurento */

#endif /*  __FILTER_HPP__ */
