/* Autogenerated with kurento-module-creator */

#ifndef __HUB_PORT_HPP__
#define __HUB_PORT_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "MediaElement.hpp"

namespace kurento
{
class HubPort;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::HubPort> &object, JsonSerializer &serializer);
}

namespace kurento
{
class Hub;
} /* kurento */

namespace kurento
{
class HubPort : public virtual MediaElement
{

public:
  HubPort () {};
  virtual ~HubPort () {};

  virtual std::string getType () const {
    return "HubPort";
  }

  virtual std::string getModule () const {
    return "kurento";
  }

  virtual void Serialize (JsonSerializer &serializer) = 0;

};

} /* kurento */

#endif /*  __HUB_PORT_HPP__ */
