/* Autogenerated with kurento-module-creator */

#ifndef __MEDIA_SESSION_STARTED_HPP__
#define __MEDIA_SESSION_STARTED_HPP__

#include <json/json.h>
#include <memory>
#include "Media.hpp"

namespace kurento
{
class MediaSessionStarted;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::MediaSessionStarted> &object, JsonSerializer &s);
}


namespace kurento
{

class MediaSessionStarted : public Media
{

public:

  MediaSessionStarted (std::shared_ptr<MediaObject> source, const std::string &type) : Media (source, type) {
  };

  MediaSessionStarted (const Json::Value &value);

  static std::string getName() {
    return "MediaSessionStarted";
  }

  virtual void Serialize (JsonSerializer &s);

protected:

  MediaSessionStarted() {};

private:

  friend void kurento::Serialize (std::shared_ptr<kurento::MediaSessionStarted> &event, JsonSerializer &s);
};

} /* kurento */

#endif /*  __MEDIA_SESSION_STARTED_HPP__ */
