/* Autogenerated with kurento-module-creator */

#ifndef __MEDIA_ELEMENT_INTERNAL_HPP__
#define __MEDIA_ELEMENT_INTERNAL_HPP__

#include "MediaElement.hpp"

namespace kurento
{
class JsonSerializer;
}

namespace kurento
{
class MediaType;
class ElementConnectionData;
class MediaElement;
class AudioCaps;
class VideoCaps;
class GstreamerDotDetails;
class Stats;
} /* kurento */

namespace kurento
{

class MediaElementMethodGetSourceConnections
{
public:
  MediaElementMethodGetSourceConnections() {}
  ~MediaElementMethodGetSourceConnections() {}

  std::vector<std::shared_ptr<ElementConnectionData>> invoke (std::shared_ptr<MediaElement> obj);
  void Serialize (JsonSerializer &serializer);

  std::shared_ptr<MediaType> getMediaType () {
    return mediaType;
  }

  void setMediaType (std::shared_ptr<MediaType> mediaType) {
    this->mediaType = mediaType;
    __isSetMediaType = true;
  }

  std::string getDescription () {
    return description;
  }

  void setDescription (const std::string &description) {
    this->description = description;
    __isSetDescription = true;
  }

private:
  std::shared_ptr<MediaType> mediaType;
  bool __isSetMediaType = false;
  std::string description;
  bool __isSetDescription = false;
};

class MediaElementMethodGetSinkConnections
{
public:
  MediaElementMethodGetSinkConnections() {}
  ~MediaElementMethodGetSinkConnections() {}

  std::vector<std::shared_ptr<ElementConnectionData>> invoke (std::shared_ptr<MediaElement> obj);
  void Serialize (JsonSerializer &serializer);

  std::shared_ptr<MediaType> getMediaType () {
    return mediaType;
  }

  void setMediaType (std::shared_ptr<MediaType> mediaType) {
    this->mediaType = mediaType;
    __isSetMediaType = true;
  }

  std::string getDescription () {
    return description;
  }

  void setDescription (const std::string &description) {
    this->description = description;
    __isSetDescription = true;
  }

private:
  std::shared_ptr<MediaType> mediaType;
  bool __isSetMediaType = false;
  std::string description;
  bool __isSetDescription = false;
};

class MediaElementMethodConnect
{
public:
  MediaElementMethodConnect() {}
  ~MediaElementMethodConnect() {}

  void invoke (std::shared_ptr<MediaElement> obj);
  void Serialize (JsonSerializer &serializer);

  std::shared_ptr<MediaElement> getSink () {
    return sink;
  }

  void setSink (std::shared_ptr<MediaElement> sink) {
    this->sink = sink;
  }

  std::shared_ptr<MediaType> getMediaType () {
    return mediaType;
  }

  void setMediaType (std::shared_ptr<MediaType> mediaType) {
    this->mediaType = mediaType;
    __isSetMediaType = true;
  }

  std::string getSourceMediaDescription () {
    return sourceMediaDescription;
  }

  void setSourceMediaDescription (const std::string &sourceMediaDescription) {
    this->sourceMediaDescription = sourceMediaDescription;
    __isSetSourceMediaDescription = true;
  }

  std::string getSinkMediaDescription () {
    return sinkMediaDescription;
  }

  void setSinkMediaDescription (const std::string &sinkMediaDescription) {
    this->sinkMediaDescription = sinkMediaDescription;
    __isSetSinkMediaDescription = true;
  }

private:
  std::shared_ptr<MediaElement> sink;
  std::shared_ptr<MediaType> mediaType;
  bool __isSetMediaType = false;
  std::string sourceMediaDescription;
  bool __isSetSourceMediaDescription = false;
  std::string sinkMediaDescription;
  bool __isSetSinkMediaDescription = false;
};

class MediaElementMethodDisconnect
{
public:
  MediaElementMethodDisconnect() {}
  ~MediaElementMethodDisconnect() {}

  void invoke (std::shared_ptr<MediaElement> obj);
  void Serialize (JsonSerializer &serializer);

  std::shared_ptr<MediaElement> getSink () {
    return sink;
  }

  void setSink (std::shared_ptr<MediaElement> sink) {
    this->sink = sink;
  }

  std::shared_ptr<MediaType> getMediaType () {
    return mediaType;
  }

  void setMediaType (std::shared_ptr<MediaType> mediaType) {
    this->mediaType = mediaType;
    __isSetMediaType = true;
  }

  std::string getSourceMediaDescription () {
    return sourceMediaDescription;
  }

  void setSourceMediaDescription (const std::string &sourceMediaDescription) {
    this->sourceMediaDescription = sourceMediaDescription;
    __isSetSourceMediaDescription = true;
  }

  std::string getSinkMediaDescription () {
    return sinkMediaDescription;
  }

  void setSinkMediaDescription (const std::string &sinkMediaDescription) {
    this->sinkMediaDescription = sinkMediaDescription;
    __isSetSinkMediaDescription = true;
  }

private:
  std::shared_ptr<MediaElement> sink;
  std::shared_ptr<MediaType> mediaType;
  bool __isSetMediaType = false;
  std::string sourceMediaDescription;
  bool __isSetSourceMediaDescription = false;
  std::string sinkMediaDescription;
  bool __isSetSinkMediaDescription = false;
};

class MediaElementMethodSetAudioFormat
{
public:
  MediaElementMethodSetAudioFormat() {}
  ~MediaElementMethodSetAudioFormat() {}

  void invoke (std::shared_ptr<MediaElement> obj);
  void Serialize (JsonSerializer &serializer);

  std::shared_ptr<AudioCaps> getCaps () {
    return caps;
  }

  void setCaps (std::shared_ptr<AudioCaps> caps) {
    this->caps = caps;
  }

private:
  std::shared_ptr<AudioCaps> caps;
};

class MediaElementMethodSetVideoFormat
{
public:
  MediaElementMethodSetVideoFormat() {}
  ~MediaElementMethodSetVideoFormat() {}

  void invoke (std::shared_ptr<MediaElement> obj);
  void Serialize (JsonSerializer &serializer);

  std::shared_ptr<VideoCaps> getCaps () {
    return caps;
  }

  void setCaps (std::shared_ptr<VideoCaps> caps) {
    this->caps = caps;
  }

private:
  std::shared_ptr<VideoCaps> caps;
};

class MediaElementMethodGetGstreamerDot
{
public:
  MediaElementMethodGetGstreamerDot() {}
  ~MediaElementMethodGetGstreamerDot() {}

  std::string invoke (std::shared_ptr<MediaElement> obj);
  void Serialize (JsonSerializer &serializer);

  std::shared_ptr<GstreamerDotDetails> getDetails () {
    return details;
  }

  void setDetails (std::shared_ptr<GstreamerDotDetails> details) {
    this->details = details;
    __isSetDetails = true;
  }

private:
  std::shared_ptr<GstreamerDotDetails> details;
  bool __isSetDetails = false;
};

class MediaElementMethodSetOutputBitrate
{
public:
  MediaElementMethodSetOutputBitrate() {}
  ~MediaElementMethodSetOutputBitrate() {}

  void invoke (std::shared_ptr<MediaElement> obj);
  void Serialize (JsonSerializer &serializer);

  int getBitrate () {
    return bitrate;
  }

  void setBitrate (int bitrate) {
    this->bitrate = bitrate;
  }

private:
  int bitrate;
};

class MediaElementMethodGetStats
{
public:
  MediaElementMethodGetStats() {}
  ~MediaElementMethodGetStats() {}

  std::map <std::string,std::shared_ptr<Stats>> invoke (std::shared_ptr<MediaElement> obj);
  void Serialize (JsonSerializer &serializer);

  std::shared_ptr<MediaType> getMediaType () {
    return mediaType;
  }

  void setMediaType (std::shared_ptr<MediaType> mediaType) {
    this->mediaType = mediaType;
    __isSetMediaType = true;
  }

private:
  std::shared_ptr<MediaType> mediaType;
  bool __isSetMediaType = false;
};

class MediaElementMethodIsMediaFlowingIn
{
public:
  MediaElementMethodIsMediaFlowingIn() {}
  ~MediaElementMethodIsMediaFlowingIn() {}

  bool invoke (std::shared_ptr<MediaElement> obj);
  void Serialize (JsonSerializer &serializer);

  std::shared_ptr<MediaType> getMediaType () {
    return mediaType;
  }

  void setMediaType (std::shared_ptr<MediaType> mediaType) {
    this->mediaType = mediaType;
  }

  std::string getSinkMediaDescription () {
    return sinkMediaDescription;
  }

  void setSinkMediaDescription (const std::string &sinkMediaDescription) {
    this->sinkMediaDescription = sinkMediaDescription;
    __isSetSinkMediaDescription = true;
  }

private:
  std::shared_ptr<MediaType> mediaType;
  std::string sinkMediaDescription;
  bool __isSetSinkMediaDescription = false;
};

class MediaElementMethodIsMediaFlowingOut
{
public:
  MediaElementMethodIsMediaFlowingOut() {}
  ~MediaElementMethodIsMediaFlowingOut() {}

  bool invoke (std::shared_ptr<MediaElement> obj);
  void Serialize (JsonSerializer &serializer);

  std::shared_ptr<MediaType> getMediaType () {
    return mediaType;
  }

  void setMediaType (std::shared_ptr<MediaType> mediaType) {
    this->mediaType = mediaType;
  }

  std::string getSourceMediaDescription () {
    return sourceMediaDescription;
  }

  void setSourceMediaDescription (const std::string &sourceMediaDescription) {
    this->sourceMediaDescription = sourceMediaDescription;
    __isSetSourceMediaDescription = true;
  }

private:
  std::shared_ptr<MediaType> mediaType;
  std::string sourceMediaDescription;
  bool __isSetSourceMediaDescription = false;
};

} /* kurento */

#endif /*  __MEDIA_ELEMENT_INTERNAL_HPP__ */
