/* Autogenerated with kurento-module-creator */

#ifndef __PASS_THROUGH_HPP__
#define __PASS_THROUGH_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "MediaElement.hpp"

namespace kurento
{
class PassThrough;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::PassThrough> &object, JsonSerializer &serializer);
}

namespace kurento
{
class MediaPipeline;
} /* kurento */

namespace kurento
{
class PassThrough : public virtual MediaElement
{

public:
  PassThrough () {};
  virtual ~PassThrough () {};

  virtual std::string getType () const {
    return "PassThrough";
  }

  virtual std::string getModule () const {
    return "kurento";
  }

  virtual void Serialize (JsonSerializer &serializer) = 0;

};

} /* kurento */

#endif /*  __PASS_THROUGH_HPP__ */
