/* Autogenerated with kurento-module-creator */

#ifndef __SDP_ENDPOINT_INTERNAL_HPP__
#define __SDP_ENDPOINT_INTERNAL_HPP__

#include "SdpEndpoint.hpp"

namespace kurento
{
class JsonSerializer;
}

namespace kurento
{

class SdpEndpointMethodGenerateOffer
{
public:
  SdpEndpointMethodGenerateOffer() {}
  ~SdpEndpointMethodGenerateOffer() {}

  std::string invoke (std::shared_ptr<SdpEndpoint> obj);
  void Serialize (JsonSerializer &serializer);

};

class SdpEndpointMethodProcessOffer
{
public:
  SdpEndpointMethodProcessOffer() {}
  ~SdpEndpointMethodProcessOffer() {}

  std::string invoke (std::shared_ptr<SdpEndpoint> obj);
  void Serialize (JsonSerializer &serializer);

  std::string getOffer () {
    return offer;
  }

  void setOffer (const std::string &offer) {
    this->offer = offer;
  }

private:
  std::string offer;
};

class SdpEndpointMethodProcessAnswer
{
public:
  SdpEndpointMethodProcessAnswer() {}
  ~SdpEndpointMethodProcessAnswer() {}

  std::string invoke (std::shared_ptr<SdpEndpoint> obj);
  void Serialize (JsonSerializer &serializer);

  std::string getAnswer () {
    return answer;
  }

  void setAnswer (const std::string &answer) {
    this->answer = answer;
  }

private:
  std::string answer;
};

class SdpEndpointMethodGetLocalSessionDescriptor
{
public:
  SdpEndpointMethodGetLocalSessionDescriptor() {}
  ~SdpEndpointMethodGetLocalSessionDescriptor() {}

  std::string invoke (std::shared_ptr<SdpEndpoint> obj);
  void Serialize (JsonSerializer &serializer);

};

class SdpEndpointMethodGetRemoteSessionDescriptor
{
public:
  SdpEndpointMethodGetRemoteSessionDescriptor() {}
  ~SdpEndpointMethodGetRemoteSessionDescriptor() {}

  std::string invoke (std::shared_ptr<SdpEndpoint> obj);
  void Serialize (JsonSerializer &serializer);

};

} /* kurento */

#endif /*  __SDP_ENDPOINT_INTERNAL_HPP__ */
