/* Autogenerated with kurento-module-creator */

#ifndef __URI_ENDPOINT_INTERNAL_HPP__
#define __URI_ENDPOINT_INTERNAL_HPP__

#include "UriEndpoint.hpp"

namespace kurento
{
class JsonSerializer;
}

namespace kurento
{

class UriEndpointMethodPause
{
public:
  UriEndpointMethodPause() {}
  ~UriEndpointMethodPause() {}

  void invoke (std::shared_ptr<UriEndpoint> obj);
  void Serialize (JsonSerializer &serializer);

};

class UriEndpointMethodStop
{
public:
  UriEndpointMethodStop() {}
  ~UriEndpointMethodStop() {}

  void invoke (std::shared_ptr<UriEndpoint> obj);
  void Serialize (JsonSerializer &serializer);

};

} /* kurento */

#endif /*  __URI_ENDPOINT_INTERNAL_HPP__ */
