/* Autogenerated with kurento-module-creator */

#ifndef __COMPOSITE_IMPL_FACTORY_HPP__
#define __COMPOSITE_IMPL_FACTORY_HPP__

#include "CompositeImpl.hpp"
#include "HubImplFactory.hpp"
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{

class CompositeImplFactory : public virtual HubImplFactory
{
public:
  CompositeImplFactory () {};

  virtual std::string getName () const {
    return "Composite";
  };

private:

  virtual MediaObjectImpl *createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const;

  MediaObjectImpl *createObject (const boost::property_tree::ptree &conf, std::shared_ptr<MediaPipeline> mediaPipeline) const;
};

} /* kurento */

#endif /*  __COMPOSITE_IMPL_FACTORY_HPP__ */