/* Autogenerated with kurento-module-creator */

#ifndef __COMPOSITE_HPP__
#define __COMPOSITE_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "Hub.hpp"

namespace kurento
{
class Composite;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::Composite> &object, JsonSerializer &serializer);
}

namespace kurento
{
class MediaPipeline;
} /* kurento */

namespace kurento
{
class Composite : public virtual Hub
{

public:
  Composite () {};
  virtual ~Composite () {};

  virtual std::string getType () const {
    return "Composite";
  }

  virtual std::string getModule () const {
    return "kurento";
  }

  virtual void Serialize (JsonSerializer &serializer) = 0;

};

} /* kurento */

#endif /*  __COMPOSITE_HPP__ */
