/* Autogenerated with kurento-module-creator */

#ifndef __DISPATCHER_IMPL_FACTORY_HPP__
#define __DISPATCHER_IMPL_FACTORY_HPP__

#include "DispatcherImpl.hpp"
#include "HubImplFactory.hpp"
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{

class DispatcherImplFactory : public virtual HubImplFactory
{
public:
  DispatcherImplFactory () {};

  virtual std::string getName () const {
    return "Dispatcher";
  };

private:

  virtual MediaObjectImpl *createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const;

  MediaObjectImpl *createObject (const boost::property_tree::ptree &conf, std::shared_ptr<MediaPipeline> mediaPipeline) const;
};

} /* kurento */

#endif /*  __DISPATCHER_IMPL_FACTORY_HPP__ */