/* Autogenerated with kurento-module-creator */

#ifndef __HTTP_POST_ENDPOINT_HPP__
#define __HTTP_POST_ENDPOINT_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "HttpEndpoint.hpp"
#include "EndOfStream.hpp"
#include <sigc++/sigc++.h>

namespace kurento
{
class HttpPostEndpoint;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::HttpPostEndpoint> &object, JsonSerializer &serializer);
}

namespace kurento
{
class MediaPipeline;
} /* kurento */

namespace kurento
{
class HttpPostEndpoint : public virtual HttpEndpoint
{

public:
  HttpPostEndpoint () {};
  virtual ~HttpPostEndpoint () {};

  virtual std::string getType () const {
    return "HttpPostEndpoint";
  }

  virtual std::string getModule () const {
    return "kurento";
  }

  virtual void Serialize (JsonSerializer &serializer) = 0;

};

} /* kurento */

#endif /*  __HTTP_POST_ENDPOINT_HPP__ */
