/* Autogenerated with kurento-module-creator */

#ifndef __HTTP_ENDPOINT_HPP__
#define __HTTP_ENDPOINT_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "SessionEndpoint.hpp"

namespace kurento
{
class HttpEndpoint;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::HttpEndpoint> &object, JsonSerializer &serializer);
}

namespace kurento
{
class HttpEndpoint : public virtual SessionEndpoint
{

public:
  HttpEndpoint () {};
  virtual ~HttpEndpoint () {};

  virtual std::string getUrl () = 0;

  virtual std::string getType () const {
    return "HttpEndpoint";
  }

  virtual std::string getModule () const {
    return "kurento";
  }

  virtual void Serialize (JsonSerializer &serializer) = 0;

};

} /* kurento */

#endif /*  __HTTP_ENDPOINT_HPP__ */
