/* Autogenerated with kurento-module-creator */

#ifndef __MIXER_IMPL_FACTORY_HPP__
#define __MIXER_IMPL_FACTORY_HPP__

#include "MixerImpl.hpp"
#include "HubImplFactory.hpp"
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{

class MixerImplFactory : public virtual HubImplFactory
{
public:
  MixerImplFactory () {};

  virtual std::string getName () const {
    return "Mixer";
  };

private:

  virtual MediaObjectImpl *createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const;

  MediaObjectImpl *createObject (const boost::property_tree::ptree &conf, std::shared_ptr<MediaPipeline> mediaPipeline) const;
};

} /* kurento */

#endif /*  __MIXER_IMPL_FACTORY_HPP__ */