/* Autogenerated with kurento-module-creator */

#ifndef __MIXER_HPP__
#define __MIXER_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "Hub.hpp"

namespace kurento
{
class Mixer;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::Mixer> &object, JsonSerializer &serializer);
}

namespace kurento
{
class MediaPipeline;
class MediaType;
class HubPort;
} /* kurento */

namespace kurento
{
class Mixer : public virtual Hub
{

public:
  Mixer () {};
  virtual ~Mixer () {};

  virtual void connect (std::shared_ptr<MediaType> media, std::shared_ptr<HubPort> source, std::shared_ptr<HubPort> sink) = 0;
  virtual void disconnect (std::shared_ptr<MediaType> media, std::shared_ptr<HubPort> source, std::shared_ptr<HubPort> sink) = 0;

  virtual std::string getType () const {
    return "Mixer";
  }

  virtual std::string getModule () const {
    return "kurento";
  }

  virtual void Serialize (JsonSerializer &serializer) = 0;

};

} /* kurento */

#endif /*  __MIXER_HPP__ */
