/* Autogenerated with kurento-module-creator */

#ifndef __RECORDER_ENDPOINT_HPP__
#define __RECORDER_ENDPOINT_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "UriEndpoint.hpp"

namespace kurento
{
class RecorderEndpoint;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::RecorderEndpoint> &object, JsonSerializer &serializer);
}

namespace kurento
{
class MediaPipeline;
class MediaProfileSpecType;
} /* kurento */

namespace kurento
{
class RecorderEndpoint : public virtual UriEndpoint
{

public:
  RecorderEndpoint () {};
  virtual ~RecorderEndpoint () {};

  virtual void record () = 0;

  virtual std::string getType () const {
    return "RecorderEndpoint";
  }

  virtual std::string getModule () const {
    return "kurento";
  }

  virtual void Serialize (JsonSerializer &serializer) = 0;

};

} /* kurento */

#endif /*  __RECORDER_ENDPOINT_HPP__ */
