/* Autogenerated with kurento-module-creator */

#ifndef __RECORDER_ENDPOINT_IMPL_FACTORY_HPP__
#define __RECORDER_ENDPOINT_IMPL_FACTORY_HPP__

#include "RecorderEndpointImpl.hpp"
#include "UriEndpointImplFactory.hpp"
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{

class RecorderEndpointImplFactory : public virtual UriEndpointImplFactory
{
public:
  RecorderEndpointImplFactory () {};

  virtual std::string getName () const {
    return "RecorderEndpoint";
  };

private:

  virtual MediaObjectImpl *createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const;

  MediaObjectImpl *createObject (const boost::property_tree::ptree &conf, std::shared_ptr<MediaPipeline> mediaPipeline, const std::string &uri, std::shared_ptr<MediaProfileSpecType> mediaProfile, bool stopOnEndOfStream) const;
};

} /* kurento */

#endif /*  __RECORDER_ENDPOINT_IMPL_FACTORY_HPP__ */