/* Autogenerated with kurento-module-creator */

#ifndef __RTP_ENDPOINT_HPP__
#define __RTP_ENDPOINT_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "BaseRtpEndpoint.hpp"
#include "OnKeySoftLimit.hpp"
#include <sigc++/sigc++.h>

namespace kurento
{
class RtpEndpoint;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::RtpEndpoint> &object, JsonSerializer &serializer);
}

namespace kurento
{
class MediaPipeline;
class SDES;
} /* kurento */

namespace kurento
{
class RtpEndpoint : public virtual BaseRtpEndpoint
{

public:
  RtpEndpoint () {};
  virtual ~RtpEndpoint () {};

  virtual std::string getType () const {
    return "RtpEndpoint";
  }

  virtual std::string getModule () const {
    return "kurento";
  }

  virtual void Serialize (JsonSerializer &serializer) = 0;

};

} /* kurento */

#endif /*  __RTP_ENDPOINT_HPP__ */
