/* Autogenerated with kurento-module-creator */

#ifndef __RTP_ENDPOINT_IMPL_FACTORY_HPP__
#define __RTP_ENDPOINT_IMPL_FACTORY_HPP__

#include "RtpEndpointImpl.hpp"
#include "BaseRtpEndpointImplFactory.hpp"
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{

class RtpEndpointImplFactory : public virtual BaseRtpEndpointImplFactory
{
public:
  RtpEndpointImplFactory () {};

  virtual std::string getName () const {
    return "RtpEndpoint";
  };

private:

  virtual MediaObjectImpl *createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const;

  MediaObjectImpl *createObject (const boost::property_tree::ptree &conf, std::shared_ptr<MediaPipeline> mediaPipeline, std::shared_ptr<SDES> crypto, bool useIpv6) const;
};

} /* kurento */

#endif /*  __RTP_ENDPOINT_IMPL_FACTORY_HPP__ */