/* Autogenerated with kurento-module-creator */

#ifndef __WEB_RTC_ENDPOINT_IMPL_FACTORY_HPP__
#define __WEB_RTC_ENDPOINT_IMPL_FACTORY_HPP__

#include "WebRtcEndpointImpl.hpp"
#include "BaseRtpEndpointImplFactory.hpp"
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{

class WebRtcEndpointImplFactory : public virtual BaseRtpEndpointImplFactory
{
public:
  WebRtcEndpointImplFactory () {};

  virtual std::string getName () const {
    return "WebRtcEndpoint";
  };

private:

  virtual MediaObjectImpl *createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const;

  MediaObjectImpl *createObject (const boost::property_tree::ptree &conf, std::shared_ptr<MediaPipeline> mediaPipeline, bool useDataChannels) const;
};

} /* kurento */

#endif /*  __WEB_RTC_ENDPOINT_IMPL_FACTORY_HPP__ */