/* Autogenerated with kurento-module-creator */

#ifndef __WEB_RTC_ENDPOINT_HPP__
#define __WEB_RTC_ENDPOINT_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "BaseRtpEndpoint.hpp"
#include "OnIceCandidate.hpp"
#include "OnIceGatheringDone.hpp"
#include "OnIceComponentStateChanged.hpp"
#include "OnDataChannelOpened.hpp"
#include "OnDataChannelClosed.hpp"
#include <sigc++/sigc++.h>

namespace kurento
{
class WebRtcEndpoint;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::WebRtcEndpoint> &object, JsonSerializer &serializer);
}

namespace kurento
{
class MediaPipeline;
class IceCandidate;
} /* kurento */

namespace kurento
{
class WebRtcEndpoint : public virtual BaseRtpEndpoint
{

public:
  WebRtcEndpoint () {};
  virtual ~WebRtcEndpoint () {};

  virtual void gatherCandidates () = 0;
  virtual void addIceCandidate (std::shared_ptr<IceCandidate> candidate) = 0;
  virtual void createDataChannel () = 0;
  virtual void createDataChannel (const std::string &label) = 0;
  virtual void createDataChannel (const std::string &label, bool ordered) = 0;
  virtual void createDataChannel (const std::string &label, bool ordered, int maxPacketLifeTime) = 0;
  virtual void createDataChannel (const std::string &label, bool ordered, int maxPacketLifeTime, int maxRetransmits) = 0;
  virtual void createDataChannel (const std::string &label, bool ordered, int maxPacketLifeTime, int maxRetransmits, const std::string &protocol) = 0;
  virtual void closeDataChannel (int channelId) = 0;

  virtual std::string getType () const {
    return "WebRtcEndpoint";
  }

  virtual std::string getModule () const {
    return "kurento";
  }

  virtual void Serialize (JsonSerializer &serializer) = 0;

  virtual std::string getStunServerAddress () = 0;
  virtual void setStunServerAddress (const std::string &stunServerAddress) = 0;

  virtual int getStunServerPort () = 0;
  virtual void setStunServerPort (int stunServerPort) = 0;

  virtual std::string getTurnUrl () = 0;
  virtual void setTurnUrl (const std::string &turnUrl) = 0;

};

} /* kurento */

#endif /*  __WEB_RTC_ENDPOINT_HPP__ */
