/* Autogenerated with kurento-module-creator */

#ifndef __BASE_RTP_ENDPOINT_IMPL_FACTORY_HPP__
#define __BASE_RTP_ENDPOINT_IMPL_FACTORY_HPP__

#include "BaseRtpEndpointImpl.hpp"
#include "SdpEndpointImplFactory.hpp"
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{

class BaseRtpEndpointImplFactory : public virtual SdpEndpointImplFactory
{
public:
  BaseRtpEndpointImplFactory () {};

  virtual std::string getName () const {
    return "BaseRtpEndpoint";
  };

};

} /* kurento */

#endif /*  __BASE_RTP_ENDPOINT_IMPL_FACTORY_HPP__ */