/* Autogenerated with kurento-module-creator */

#ifndef __HUB_PORT_IMPL_FACTORY_HPP__
#define __HUB_PORT_IMPL_FACTORY_HPP__

#include "HubPortImpl.hpp"
#include "MediaElementImplFactory.hpp"
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{

class HubPortImplFactory : public virtual MediaElementImplFactory
{
public:
  HubPortImplFactory () {};

  virtual std::string getName () const {
    return "HubPort";
  };

private:

  virtual MediaObjectImpl *createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const;

  MediaObjectImpl *createObject (const boost::property_tree::ptree &conf, std::shared_ptr<Hub> hub) const;
};

} /* kurento */

#endif /*  __HUB_PORT_IMPL_FACTORY_HPP__ */