/* Autogenerated with kurento-module-creator */

#ifndef __MEDIA_PIPELINE_IMPL_FACTORY_HPP__
#define __MEDIA_PIPELINE_IMPL_FACTORY_HPP__

#include "MediaPipelineImpl.hpp"
#include "MediaObjectImplFactory.hpp"
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{

class MediaPipelineImplFactory : public virtual MediaObjectImplFactory
{
public:
  MediaPipelineImplFactory () {};

  virtual std::string getName () const {
    return "MediaPipeline";
  };

private:

  virtual MediaObjectImpl *createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const;

  MediaObjectImpl *createObject (const boost::property_tree::ptree &conf) const;
};

} /* kurento */

#endif /*  __MEDIA_PIPELINE_IMPL_FACTORY_HPP__ */