/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "UriEndpointImpl.hpp"
#include "UriEndpointImplFactory.hpp"
#include "UriEndpointInternal.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

using kurento::KurentoException;

namespace kurento
{

void
UriEndpointImpl::invoke (std::shared_ptr<MediaObjectImpl> obj, const std::string &methodName, const Json::Value &params, Json::Value &response)
{
  if (methodName == "pause") {
    kurento::JsonSerializer s (false);
    UriEndpointMethodPause method;

    s.JsonValue = params;
    method.Serialize (s);

    method.invoke (std::dynamic_pointer_cast<UriEndpoint> (obj) );
    return;
  }

  if (methodName == "stop") {
    kurento::JsonSerializer s (false);
    UriEndpointMethodStop method;

    s.JsonValue = params;
    method.Serialize (s);

    method.invoke (std::dynamic_pointer_cast<UriEndpoint> (obj) );
    return;
  }

  if (methodName == "getUri") {
    std::string ret;
    JsonSerializer responseSerializer (true);

    ret = std::dynamic_pointer_cast<UriEndpoint> (obj)->getUri ();
    responseSerializer.SerializeNVP (ret);
    response = responseSerializer.JsonValue["ret"];
    return;
  }

  EndpointImpl::invoke (obj, methodName, params, response);
}

bool
UriEndpointImpl::connect (const std::string &eventType, std::shared_ptr<EventHandler> handler)
{

  return EndpointImpl::connect (eventType, handler);
}

void
UriEndpointImpl::Serialize (JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    try {
      Json::Value v (getId() );

      serializer.JsonValue = v;
    } catch (std::bad_cast &e) {
    }
  } else {
    throw KurentoException (MARSHALL_ERROR,
                            "'UriEndpointImpl' cannot be deserialized as an object");
  }
}
} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::UriEndpointImpl> &object, JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    if (object) {
      object->Serialize (serializer);
    }
  } else {
    std::shared_ptr<kurento::MediaObjectImpl> aux;
    aux = kurento::UriEndpointImplFactory::getObject (JsonFixes::getString(serializer.JsonValue) );
    object = std::dynamic_pointer_cast<kurento::UriEndpointImpl> (aux);
  }
}

void
Serialize (std::shared_ptr<kurento::UriEndpoint> &object, JsonSerializer &serializer)
{
  std::shared_ptr<kurento::UriEndpointImpl> aux = std::dynamic_pointer_cast<kurento::UriEndpointImpl> (object);

  Serialize (aux, serializer);
  object = std::dynamic_pointer_cast <kurento::UriEndpoint> (aux);
}

} /* kurento */