/* Autogenerated with kurento-module-creator */

#ifndef __HUB_HPP__
#define __HUB_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "MediaObject.hpp"

namespace kurento
{
class Hub;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::Hub> &object, JsonSerializer &serializer);
}

namespace kurento
{
class GstreamerDotDetails;
} /* kurento */

namespace kurento
{
class Hub : public virtual MediaObject
{

public:
  Hub () {};
  virtual ~Hub () {};

  virtual std::string getGstreamerDot () = 0;
  virtual std::string getGstreamerDot (std::shared_ptr<GstreamerDotDetails> details) = 0;

  virtual std::string getType () const {
    return "Hub";
  }

  virtual std::string getModule () const {
    return "kurento";
  }

  virtual void Serialize (JsonSerializer &serializer) = 0;

};

} /* kurento */

#endif /*  __HUB_HPP__ */
