/* Autogenerated with kurento-module-creator */

#ifndef __HUB_IMPL_FACTORY_HPP__
#define __HUB_IMPL_FACTORY_HPP__

#include "HubImpl.hpp"
#include "MediaObjectImplFactory.hpp"
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{

class HubImplFactory : public virtual MediaObjectImplFactory
{
public:
  HubImplFactory () {};

  virtual std::string getName () const {
    return "Hub";
  };

};

} /* kurento */

#endif /*  __HUB_IMPL_FACTORY_HPP__ */