/* Autogenerated with kurento-module-creator */

#ifndef __SERVER_MANAGER_IMPL_FACTORY_HPP__
#define __SERVER_MANAGER_IMPL_FACTORY_HPP__

#include "ServerManagerImpl.hpp"
#include "MediaObjectImplFactory.hpp"
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{

class ServerManagerImplFactory : public virtual MediaObjectImplFactory
{
public:
  ServerManagerImplFactory () {};

  virtual std::string getName () const {
    return "ServerManager";
  };

};

} /* kurento */

#endif /*  __SERVER_MANAGER_IMPL_FACTORY_HPP__ */