/* Autogenerated with kurento-module-creator */

#ifndef __SESSION_ENDPOINT_HPP__
#define __SESSION_ENDPOINT_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "Endpoint.hpp"
#include "MediaSessionTerminated.hpp"
#include "MediaSessionStarted.hpp"
#include <sigc++/sigc++.h>

namespace kurento
{
class SessionEndpoint;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::SessionEndpoint> &object, JsonSerializer &serializer);
}

namespace kurento
{
class SessionEndpoint : public virtual Endpoint
{

public:
  SessionEndpoint () {};
  virtual ~SessionEndpoint () {};

  virtual std::string getType () const {
    return "SessionEndpoint";
  }

  virtual std::string getModule () const {
    return "kurento";
  }

  virtual void Serialize (JsonSerializer &serializer) = 0;

};

} /* kurento */

#endif /*  __SESSION_ENDPOINT_HPP__ */
