/* Autogenerated with kurento-module-creator */

#ifndef __URI_ENDPOINT_HPP__
#define __URI_ENDPOINT_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "Endpoint.hpp"

namespace kurento
{
class UriEndpoint;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::UriEndpoint> &object, JsonSerializer &serializer);
}

namespace kurento
{
class UriEndpoint : public virtual Endpoint
{

public:
  UriEndpoint () {};
  virtual ~UriEndpoint () {};

  virtual void pause () = 0;
  virtual void stop () = 0;

  virtual std::string getType () const {
    return "UriEndpoint";
  }

  virtual std::string getModule () const {
    return "kurento";
  }

  virtual void Serialize (JsonSerializer &serializer) = 0;

  virtual std::string getUri () = 0;

};

} /* kurento */

#endif /*  __URI_ENDPOINT_HPP__ */
