/* Autogenerated with kurento-module-creator */

#ifndef __FACE_OVERLAY_FILTER_IMPL_FACTORY_HPP__
#define __FACE_OVERLAY_FILTER_IMPL_FACTORY_HPP__

#include "FaceOverlayFilterImpl.hpp"
#include "FilterImplFactory.hpp"
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{

class FaceOverlayFilterImplFactory : public virtual FilterImplFactory
{
public:
  FaceOverlayFilterImplFactory () {};

  virtual std::string getName () const {
    return "FaceOverlayFilter";
  };

private:

  virtual MediaObjectImpl *createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const;

  MediaObjectImpl *createObject (const boost::property_tree::ptree &conf, std::shared_ptr<MediaPipeline> mediaPipeline) const;
};

} /* kurento */

#endif /*  __FACE_OVERLAY_FILTER_IMPL_FACTORY_HPP__ */