/* Autogenerated with kurento-module-creator */

#ifndef __GSTREAMER_FILTER_HPP__
#define __GSTREAMER_FILTER_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "Filter.hpp"

namespace kurento
{
class GStreamerFilter;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::GStreamerFilter> &object, JsonSerializer &serializer);
}

namespace kurento
{
class MediaPipeline;
class FilterType;
} /* kurento */

namespace kurento
{
class GStreamerFilter : public virtual Filter
{

public:
  GStreamerFilter () {};
  virtual ~GStreamerFilter () {};

  virtual std::string getType () const {
    return "GStreamerFilter";
  }

  virtual std::string getModule () const {
    return "kurento";
  }

  virtual void Serialize (JsonSerializer &serializer) = 0;

  virtual std::string getCommand () = 0;

};

} /* kurento */

#endif /*  __GSTREAMER_FILTER_HPP__ */
