/* Autogenerated with kurento-module-creator */

#ifndef __IMAGE_OVERLAY_FILTER_HPP__
#define __IMAGE_OVERLAY_FILTER_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "Filter.hpp"

namespace kurento
{
class ImageOverlayFilter;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::ImageOverlayFilter> &object, JsonSerializer &serializer);
}

namespace kurento
{
class MediaPipeline;
} /* kurento */

namespace kurento
{
class ImageOverlayFilter : public virtual Filter
{

public:
  ImageOverlayFilter () {};
  virtual ~ImageOverlayFilter () {};

  virtual void removeImage (const std::string &id) = 0;
  virtual void addImage (const std::string &id, const std::string &uri, float offsetXPercent, float offsetYPercent, float widthPercent, float heightPercent, bool keepAspectRatio, bool center) = 0;

  virtual std::string getType () const {
    return "ImageOverlayFilter";
  }

  virtual std::string getModule () const {
    return "kurento";
  }

  virtual void Serialize (JsonSerializer &serializer) = 0;

};

} /* kurento */

#endif /*  __IMAGE_OVERLAY_FILTER_HPP__ */
