/* Autogenerated with kurento-module-creator */

#ifndef __OPEN_CVFILTER_HPP__
#define __OPEN_CVFILTER_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "Filter.hpp"

namespace kurento
{
class OpenCVFilter;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::OpenCVFilter> &object, JsonSerializer &serializer);
}

namespace kurento
{
class OpenCVFilter : public virtual Filter
{

public:
  OpenCVFilter () {};
  virtual ~OpenCVFilter () {};

  virtual std::string getType () const {
    return "OpenCVFilter";
  }

  virtual std::string getModule () const {
    return "kurento";
  }

  virtual void Serialize (JsonSerializer &serializer) = 0;

};

} /* kurento */

#endif /*  __OPEN_CVFILTER_HPP__ */
