/* Autogenerated with kurento-module-creator */

#ifndef __ZBAR_FILTER_IMPL_FACTORY_HPP__
#define __ZBAR_FILTER_IMPL_FACTORY_HPP__

#include "ZBarFilterImpl.hpp"
#include "FilterImplFactory.hpp"
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{

class ZBarFilterImplFactory : public virtual FilterImplFactory
{
public:
  ZBarFilterImplFactory () {};

  virtual std::string getName () const {
    return "ZBarFilter";
  };

private:

  virtual MediaObjectImpl *createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const;

  MediaObjectImpl *createObject (const boost::property_tree::ptree &conf, std::shared_ptr<MediaPipeline> mediaPipeline) const;
};

} /* kurento */

#endif /*  __ZBAR_FILTER_IMPL_FACTORY_HPP__ */