/* Autogenerated with kurento-module-creator */

#ifndef __MEDIA_OBJECT_HPP__
#define __MEDIA_OBJECT_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "Error.hpp"
#include <sigc++/sigc++.h>

namespace kurento
{
class MediaObject;
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::MediaObject> &object, JsonSerializer &serializer);
}

namespace kurento
{
class Tag;
class MediaPipeline;
class MediaObject;
} /* kurento */

namespace kurento
{
class MediaObject : public std::enable_shared_from_this<MediaObject>
{

public:
  MediaObject () {};
  virtual ~MediaObject () {};

  virtual void addTag (const std::string &key, const std::string &value) = 0;
  virtual void removeTag (const std::string &key) = 0;
  virtual std::string getTag (const std::string &key) = 0;
  virtual std::vector<std::shared_ptr<Tag>> getTags () = 0;

  virtual std::string getType () const {
    return "MediaObject";
  }

  virtual std::string getModule () const {
    return "kurento";
  }

  virtual void Serialize (JsonSerializer &serializer) = 0;

  virtual std::shared_ptr<MediaPipeline> getMediaPipeline () = 0;

  virtual std::shared_ptr<MediaObject> getParent () = 0;

  virtual std::string getId () = 0;

  virtual std::vector<std::shared_ptr<MediaObject>> getChilds () = 0;

  virtual std::string getName () = 0;
  virtual void setName (const std::string &name) = 0;

  virtual bool getSendTagsInEvents () = 0;
  virtual void setSendTagsInEvents (bool sendTagsInEvents) = 0;

  virtual int getCreationTime () = 0;

};

} /* kurento */

#endif /*  __MEDIA_OBJECT_HPP__ */

